// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :exec
INSERT INTO client.clients (
    id, clerk_user_id,
    first_name, last_name, email, phone, notes, can_pay_later,
    created_at, updated_at
) VALUES (
    $1, $2,
    $3, $4, $5, $6, $7, $8,
    $9, $10
)
`

type CreateClientParams struct {
	ID          pgtype.UUID
	ClerkUserID string
	FirstName   string
	LastName    string
	Email       string
	Phone       pgtype.Text
	Notes       pgtype.Text
	CanPayLater bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) error {
	_, err := q.db.Exec(ctx, createClient,
		arg.ID,
		arg.ClerkUserID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Notes,
		arg.CanPayLater,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getClientByClerkUserID = `-- name: GetClientByClerkUserID :one
SELECT id, clerk_user_id,
       first_name, last_name, email, phone, notes, can_pay_later,
       created_at, updated_at
FROM client.clients
WHERE clerk_user_id = $1
`

func (q *Queries) GetClientByClerkUserID(ctx context.Context, clerkUserID string) (ClientClient, error) {
	row := q.db.QueryRow(ctx, getClientByClerkUserID, clerkUserID)
	var i ClientClient
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Notes,
		&i.CanPayLater,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, clerk_user_id,
       first_name, last_name, email, phone, notes, can_pay_later,
       created_at, updated_at
FROM client.clients
WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id pgtype.UUID) (ClientClient, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i ClientClient
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Notes,
		&i.CanPayLater,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateClient = `-- name: UpdateClient :execrows
UPDATE client.clients
SET
    phone         = COALESCE($3, phone),
    notes         = COALESCE($4, notes),
    can_pay_later = COALESCE($5, can_pay_later),
    updated_at    = $2
WHERE id = $1
`

type UpdateClientParams struct {
	ID          pgtype.UUID
	UpdatedAt   pgtype.Timestamptz
	Phone       pgtype.Text
	Notes       pgtype.Text
	CanPayLater pgtype.Bool
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateClient,
		arg.ID,
		arg.UpdatedAt,
		arg.Phone,
		arg.Notes,
		arg.CanPayLater,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
