// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ClientClient struct {
	ID          pgtype.UUID
	ClerkUserID string
	FirstName   string
	LastName    string
	Email       string
	Phone       pgtype.Text
	Notes       pgtype.Text
	CanPayLater bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
