// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateClient(ctx context.Context, arg CreateClientParams) error
	GetClientByClerkUserID(ctx context.Context, clerkUserID string) (ClientClient, error)
	GetClientByID(ctx context.Context, id pgtype.UUID) (ClientClient, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
