// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ProofProof struct {
	ID                 pgtype.UUID
	BookedAt           pgtype.Timestamptz
	OperatorName       string
	OperatorSiret      string
	OperatorEvtcNumber string
	VehicleNumberPlate string
	ClientFirstName    string
	ClientLastName     string
	ClientPhone        pgtype.Text
	PickupAddress      string
	DropoffAddress     string
	ScheduledAt        pgtype.Timestamptz
	ProofHash          pgtype.Text
	BookingID          pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
