// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: proofs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProof = `-- name: CreateProof :exec
INSERT INTO proof.proofs (
    id, booked_at,
    operator_name, operator_siret, operator_evtc_number,
    vehicle_number_plate,
    client_first_name, client_last_name, client_phone,
    pickup_address, dropoff_address, scheduled_at,
    proof_hash,
    booking_id,
    created_at, updated_at
) VALUES (
    $1, $2,
    $3, $4, $5,
    $6,
    $7, $8, $9,
    $10, $11, $12,
    $13,
    $14,
    $15, $16
)
`

type CreateProofParams struct {
	ID                 pgtype.UUID
	BookedAt           pgtype.Timestamptz
	OperatorName       string
	OperatorSiret      string
	OperatorEvtcNumber string
	VehicleNumberPlate string
	ClientFirstName    string
	ClientLastName     string
	ClientPhone        pgtype.Text
	PickupAddress      string
	DropoffAddress     string
	ScheduledAt        pgtype.Timestamptz
	ProofHash          pgtype.Text
	BookingID          pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) CreateProof(ctx context.Context, arg CreateProofParams) error {
	_, err := q.db.Exec(ctx, createProof,
		arg.ID,
		arg.BookedAt,
		arg.OperatorName,
		arg.OperatorSiret,
		arg.OperatorEvtcNumber,
		arg.VehicleNumberPlate,
		arg.ClientFirstName,
		arg.ClientLastName,
		arg.ClientPhone,
		arg.PickupAddress,
		arg.DropoffAddress,
		arg.ScheduledAt,
		arg.ProofHash,
		arg.BookingID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getProofByBookingID = `-- name: GetProofByBookingID :one
SELECT id, booked_at,
       operator_name, operator_siret, operator_evtc_number,
       vehicle_number_plate,
       client_first_name, client_last_name, client_phone,
       pickup_address, dropoff_address, scheduled_at,
       proof_hash,
       booking_id,
       created_at, updated_at
FROM proof.proofs
WHERE booking_id = $1
`

func (q *Queries) GetProofByBookingID(ctx context.Context, bookingID pgtype.UUID) (ProofProof, error) {
	row := q.db.QueryRow(ctx, getProofByBookingID, bookingID)
	var i ProofProof
	err := row.Scan(
		&i.ID,
		&i.BookedAt,
		&i.OperatorName,
		&i.OperatorSiret,
		&i.OperatorEvtcNumber,
		&i.VehicleNumberPlate,
		&i.ClientFirstName,
		&i.ClientLastName,
		&i.ClientPhone,
		&i.PickupAddress,
		&i.DropoffAddress,
		&i.ScheduledAt,
		&i.ProofHash,
		&i.BookingID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProofByID = `-- name: GetProofByID :one
SELECT id, booked_at,
       operator_name, operator_siret, operator_evtc_number,
       vehicle_number_plate,
       client_first_name, client_last_name, client_phone,
       pickup_address, dropoff_address, scheduled_at,
       proof_hash,
       booking_id,
       created_at, updated_at
FROM proof.proofs
WHERE id = $1
`

func (q *Queries) GetProofByID(ctx context.Context, id pgtype.UUID) (ProofProof, error) {
	row := q.db.QueryRow(ctx, getProofByID, id)
	var i ProofProof
	err := row.Scan(
		&i.ID,
		&i.BookedAt,
		&i.OperatorName,
		&i.OperatorSiret,
		&i.OperatorEvtcNumber,
		&i.VehicleNumberPlate,
		&i.ClientFirstName,
		&i.ClientLastName,
		&i.ClientPhone,
		&i.PickupAddress,
		&i.DropoffAddress,
		&i.ScheduledAt,
		&i.ProofHash,
		&i.BookingID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProofHash = `-- name: UpdateProofHash :execrows
UPDATE proof.proofs
SET proof_hash = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateProofHashParams struct {
	ID        pgtype.UUID
	ProofHash pgtype.Text
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateProofHash(ctx context.Context, arg UpdateProofHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProofHash, arg.ID, arg.ProofHash, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
