// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateProof(ctx context.Context, arg CreateProofParams) error
	GetProofByBookingID(ctx context.Context, bookingID pgtype.UUID) (ProofProof, error)
	GetProofByID(ctx context.Context, id pgtype.UUID) (ProofProof, error)
	UpdateProofHash(ctx context.Context, arg UpdateProofHashParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
