booking:  DATABASE_URL=$BOOKING_SERVICE_DB_URL PORT=$BOOKING_SERVICE_PORT VALKEY_URL=$VALKEY_URL go run ./cmd/booking-api
client:   DATABASE_URL=$CLIENT_SERVICE_DB_URL PORT=$CLIENT_SERVICE_PORT VALKEY_URL=$VALKEY_URL go run ./cmd/client-api
fleet:    DATABASE_URL=$FLEET_SERVICE_DB_URL PORT=$FLEET_SERVICE_PORT VALKEY_URL=$VALKEY_URL go run ./cmd/fleet-api
gateway:  PORT=$GATEWAY_PORT CLERK_JWKS_URL=$CLERK_JWKS_URL go run ./cmd/gateway
proof: DATABASE_URL=$PROOF_SERVICE_DB_URL PORT=$PROOF_SERVICE_PORT VALKEY_URL=$VALKEY_URL FLEET_SERVICE_URL=$FLEET_SERVICE_INTERNAL_URL CLIENT_SERVICE_URL=$CLIENT_SERVICE_INTERNAL_URL OPERATOR_NAME=$OPERATOR_NAME OPERATOR_SIRET=$OPERATOR_SIRET OPERATOR_EVTC_NUMBER=$OPERATOR_EVTC_NUMBER go run ./cmd/proof-api
