// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FleetVehicle struct {
	ID          pgtype.UUID
	NumberPlate string
	Brand       string
	Model       string
	Year        int64
	Active      bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
