// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateVehicle(ctx context.Context, arg CreateVehicleParams) error
	GetVehicleByID(ctx context.Context, id pgtype.UUID) (FleetVehicle, error)
	ListActiveVehicles(ctx context.Context) ([]FleetVehicle, error)
	UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
