// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehicles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVehicle = `-- name: CreateVehicle :exec
INSERT INTO fleet.vehicles (
    id, number_plate, brand, model, year, active, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type CreateVehicleParams struct {
	ID          pgtype.UUID
	NumberPlate string
	Brand       string
	Model       string
	Year        int64
	Active      bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) error {
	_, err := q.db.Exec(ctx, createVehicle,
		arg.ID,
		arg.NumberPlate,
		arg.Brand,
		arg.Model,
		arg.Year,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getVehicleByID = `-- name: GetVehicleByID :one
SELECT id, number_plate, brand, model, year, active, created_at, updated_at
FROM fleet.vehicles
WHERE id = $1
`

func (q *Queries) GetVehicleByID(ctx context.Context, id pgtype.UUID) (FleetVehicle, error) {
	row := q.db.QueryRow(ctx, getVehicleByID, id)
	var i FleetVehicle
	err := row.Scan(
		&i.ID,
		&i.NumberPlate,
		&i.Brand,
		&i.Model,
		&i.Year,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveVehicles = `-- name: ListActiveVehicles :many
SELECT id, number_plate, brand, model, year, active, created_at, updated_at
FROM fleet.vehicles
WHERE active = true
ORDER BY brand, model
`

func (q *Queries) ListActiveVehicles(ctx context.Context) ([]FleetVehicle, error) {
	rows, err := q.db.Query(ctx, listActiveVehicles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FleetVehicle
	for rows.Next() {
		var i FleetVehicle
		if err := rows.Scan(
			&i.ID,
			&i.NumberPlate,
			&i.Brand,
			&i.Model,
			&i.Year,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicle = `-- name: UpdateVehicle :execrows
UPDATE fleet.vehicles
SET
    number_plate = COALESCE($2, number_plate),
    brand        = COALESCE($3, brand),
    model        = COALESCE($4, model),
    year         = COALESCE($5, year),
    active       = COALESCE($6, active),
    updated_at   = $7
WHERE id = $1
`

type UpdateVehicleParams struct {
	ID          pgtype.UUID
	NumberPlate string
	Brand       string
	Model       string
	Year        int64
	Active      bool
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVehicle,
		arg.ID,
		arg.NumberPlate,
		arg.Brand,
		arg.Model,
		arg.Year,
		arg.Active,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
