// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :exec
INSERT INTO booking.bookings (
    id, client_id, vehicle_id,
    scheduled_at, pickup_address, dropoff_address,
    status, total_amount, tax_rate_basis_points,
    estimated_km, co2_grams,
    created_at, updated_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11,
    $12, $13
)
`

type CreateBookingParams struct {
	ID                 pgtype.UUID
	ClientID           pgtype.UUID
	VehicleID          pgtype.UUID
	ScheduledAt        pgtype.Timestamptz
	PickupAddress      string
	DropoffAddress     string
	Status             BookingBookingStatus
	TotalAmount        pgtype.Int4
	TaxRateBasisPoints pgtype.Int4
	EstimatedKm        pgtype.Float8
	Co2Grams           pgtype.Int4
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) error {
	_, err := q.db.Exec(ctx, createBooking,
		arg.ID,
		arg.ClientID,
		arg.VehicleID,
		arg.ScheduledAt,
		arg.PickupAddress,
		arg.DropoffAddress,
		arg.Status,
		arg.TotalAmount,
		arg.TaxRateBasisPoints,
		arg.EstimatedKm,
		arg.Co2Grams,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getBookingByID = `-- name: GetBookingByID :one
SELECT id, client_id, vehicle_id,
       scheduled_at, pickup_address, dropoff_address,
       status, total_amount, tax_rate_basis_points,
       estimated_km, co2_grams,
       external_invoice_id, invoice_url,
       created_at, updated_at
FROM booking.bookings
WHERE id = $1
`

func (q *Queries) GetBookingByID(ctx context.Context, id pgtype.UUID) (BookingBooking, error) {
	row := q.db.QueryRow(ctx, getBookingByID, id)
	var i BookingBooking
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.VehicleID,
		&i.ScheduledAt,
		&i.PickupAddress,
		&i.DropoffAddress,
		&i.Status,
		&i.TotalAmount,
		&i.TaxRateBasisPoints,
		&i.EstimatedKm,
		&i.Co2Grams,
		&i.ExternalInvoiceID,
		&i.InvoiceUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookingsByClientID = `-- name: ListBookingsByClientID :many
SELECT id, client_id, vehicle_id,
       scheduled_at, pickup_address, dropoff_address,
       status, total_amount, tax_rate_basis_points,
       estimated_km, co2_grams,
       external_invoice_id, invoice_url,
       created_at, updated_at
FROM booking.bookings
WHERE client_id = $1
ORDER BY scheduled_at DESC
`

func (q *Queries) ListBookingsByClientID(ctx context.Context, clientID pgtype.UUID) ([]BookingBooking, error) {
	rows, err := q.db.Query(ctx, listBookingsByClientID, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingBooking
	for rows.Next() {
		var i BookingBooking
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.VehicleID,
			&i.ScheduledAt,
			&i.PickupAddress,
			&i.DropoffAddress,
			&i.Status,
			&i.TotalAmount,
			&i.TaxRateBasisPoints,
			&i.EstimatedKm,
			&i.Co2Grams,
			&i.ExternalInvoiceID,
			&i.InvoiceUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingInvoice = `-- name: UpdateBookingInvoice :execrows
UPDATE booking.bookings
SET external_invoice_id = $2,
    invoice_url         = $3,
    updated_at          = $4
WHERE id = $1
`

type UpdateBookingInvoiceParams struct {
	ID                pgtype.UUID
	ExternalInvoiceID pgtype.Text
	InvoiceUrl        pgtype.Text
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) UpdateBookingInvoice(ctx context.Context, arg UpdateBookingInvoiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBookingInvoice,
		arg.ID,
		arg.ExternalInvoiceID,
		arg.InvoiceUrl,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :execrows
UPDATE booking.bookings
SET status     = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateBookingStatusParams struct {
	ID        pgtype.UUID
	Status    BookingBookingStatus
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBookingStatus, arg.ID, arg.Status, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
