// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BookingBookingStatus string

const (
	BookingBookingStatusPENDING   BookingBookingStatus = "PENDING"
	BookingBookingStatusCONFIRMED BookingBookingStatus = "CONFIRMED"
	BookingBookingStatusCOMPLETED BookingBookingStatus = "COMPLETED"
	BookingBookingStatusCANCELLED BookingBookingStatus = "CANCELLED"
)

func (e *BookingBookingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BookingBookingStatus(s)
	case string:
		*e = BookingBookingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BookingBookingStatus: %T", src)
	}
	return nil
}

type NullBookingBookingStatus struct {
	BookingBookingStatus BookingBookingStatus
	Valid                bool // Valid is true if BookingBookingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBookingBookingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BookingBookingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BookingBookingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBookingBookingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BookingBookingStatus), nil
}

type BookingBooking struct {
	ID                 pgtype.UUID
	ClientID           pgtype.UUID
	VehicleID          pgtype.UUID
	ScheduledAt        pgtype.Timestamptz
	PickupAddress      string
	DropoffAddress     string
	Status             BookingBookingStatus
	TotalAmount        pgtype.Int4
	TaxRateBasisPoints pgtype.Int4
	EstimatedKm        pgtype.Float8
	Co2Grams           pgtype.Int4
	ExternalInvoiceID  pgtype.Text
	InvoiceUrl         pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}
