// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateBooking(ctx context.Context, arg CreateBookingParams) error
	GetBookingByID(ctx context.Context, id pgtype.UUID) (GetBookingByIDRow, error)
	ListBookingsByClientID(ctx context.Context, clientID pgtype.UUID) ([]ListBookingsByClientIDRow, error)
	UpdateBookingCoordinates(ctx context.Context, arg UpdateBookingCoordinatesParams) error
	UpdateBookingInvoice(ctx context.Context, arg UpdateBookingInvoiceParams) (int64, error)
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
